---

- import_tasks: setup-Debian.yml
  when: (ruby_install_from_source == false) and (ansible_os_family == 'Debian')

- import_tasks: install-from-source.yml
  when: ruby_install_from_source == true

# Install Bundler and configured gems.
- name: Install Bundler for Ruby 2.3.0
  gem:
    name: bundler
    version: 1.17.3
    state: present
    user_install: no
  become: yes

- name: Install configured gems.
  gem: "name={{ item }} state=present"
  become: yes
  become_user: "{{ ruby_install_gems_user }}"
  with_items: "{{ ruby_install_gems }}"
