---
- name: Set up Zookeeper user and group
  hosts: all
  become: yes
  vars:
    zookeeper_user: "zookeeper"  # Replace with the actual user/group name

  tasks:
    - name: Setup group
      group:
        name: "{{ zookeeper_user }}"
        system: yes

    - name: Setup user
      user:
        name: "{{ zookeeper_user }}"
        system: yes
        group: "{{ zookeeper_user }}"

    - include_tasks: Debian.yml
      when: ansible_os_family == 'Debian'

    - include_tasks: RedHat.yml
      when: ansible_os_family == 'RedHat'
